import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";

export async function getStaticProps() {

  type launchesPast = {
    mission_name: "Starlink-15 (v1.0)"
    __typename: "Launch"
  }
  const { data } = await client.query({
    query: gql`
    query {
      launchesPast {
        mission_name
      }
    }
    `,
  });

  return {
    props: {
      launchesPast: data.launchesPast as launchesPast,
    },
  };
}

export default function Home(props: any) {
  console.log('launchesPast:', props.launchesPast)
  return (
    <div className={styles.container}>
      <Head>
        <title>{props.launchesPast[0].mission_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Last Nasa Space Mission:
        </h1>
        <p className={styles.description}>{props.launchesPast[0].mission_name}</p>

      </main>
    </div>
  )
}
